### ISSUE TITLE
Придумать название статьи

### ISSUE THREAD

**Issue by iradche** [scats/University-LOD-platform#1]

**Comment by nav-mike** [comment]
https://docs.google.com/document/d/1ktxZoKgESHNMOWNPFvkYxROam7hYypX5h9dlMibiMfM/edit?usp=sharing

**Comment by iradche** [comment]
Предварительный дедлайн: начало ноября
Название: Особенности и методика разработки платформы связанных открытых данных в университете

**Comment by iradche** [comment]
Особенности и методика разработки платформы связанных открытых данных в университете
